from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.constants.complaint import MessageRole, ComplaintStatus
from app.database.models import Complaint, ComplaintMessage
from app.schemas.complaint import ComplaintStructuredUpdate


def create_complaint(
        db:Session,
        user_id:int,
        first_message:str,
)->Complaint:
    """
    Creates a new complaint and stores the user's first message.

    Args:
        db: 
            Active SQLAlchemy database session.
        user_id:
            id of authenticated user creating the complaint.
        
        first_message:
            Self explanatory lol
    
    A newly created SQLAlchemy Complaint object wihich we will further use
    """

    #Creating the overa;; complaint case
    complaint = Complaint(
        user_id=user_id,
    )

    db.add(complaint)

    #We will use flush, it sends the INSER to postgres WITHOUT ENDING
    # the transaction. This will give us complaint.id so that first 
    # message can reference it 

    db.flush()

    # We will store the first message as part of thhisi
    # complaint conversation 
    message = ComplaintMessage(
        complaint_id = complaint.id,
        role=MessageRole.USER,
        content=first_message,
    )

    db.add(message)

    # Saving both the complaint and it's first message together.
    db.commit()

    # Reloading the complaint using values generated by PostgreSQL
    # such as id, created_at and default status.
    db.refresh(complaint)

    return complaint

def add_complaint_message(
        db: Session,
        complaint_id:int,
        content:str,
        role:MessageRole,
):
    """
    Adding a user OR aI assistanf message to an existing complaint,
    although we are not adding it to complaint table but 
    complaint_message table

    Every conversation turn becomes a separate row in the complaint_
    message table
    """

    message = ComplaintMessage(
        complaint_id = complaint_id,
        content=content,
        role=role,
    )
    db.add(message)
    db.commit()
    db.refresh(message)

    return message

def get_complaint_by_id(
    db:Session,
    complaint_id:int,
    user_id:int,
)->Complaint|None:
    """
    We want to return Complaint by id, but only to authenticated user.
    We are putting ownership check to prevent another users from 
    guessing others id
    """

    statement = (
        select(Complaint)
        .options(selectinload(Complaint.messages))
        .where(
            Complaint.id == complaint_id,
            Complaint.user_id == user_id,
        )
    )

    return db.scalar(statement)

def get_user_complaint(
        db:Session,
        complaint_id:int,
        user_id: int,
)-> Complaint | None:
    """
    Retrieve a complaint only when it belongs to a particular
    user

    There will be ownership check
    """
    statement = (
        select(Complaint)
        .options(
            selectinload(Complaint.messages),
            selectinload(Complaint.authority),
            )
        .where(
            Complaint.id==complaint_id,
            Complaint.user_id == user_id,
        )
    )
    return db.scalar(statement)


def get_user_complaints(
        db:Session,
        user_id:int,
)->list[Complaint]:
    """
    We will return list of all complaints made by a particular user

    The new complaint will come first
    """
    statement = (
        select(Complaint)
        .options(
            selectinload(Complaint.authority),
        )
        .where(Complaint.user_id==user_id)
        .order_by(Complaint.created_at.desc())
    )

    return list(db.scalars(statement).all())

def update_complaint_structured_data(
        db:Session,
        complaint: Complaint,
        update_data: ComplaintStructuredUpdate,
) -> Complaint:
    """
    Update structured fields extracted from the conversation
    
    Later, the LLM will produce ComplaintStructuredUpdate data.

    Currently we can test it manually
    Changed ComplaintStructuredUpdate to ComplaintAnalysis
    """

    # model_dump(exclude_unset=True) returns only the fields
    # that were actually supplied. Therefore the existing values in 
    # complaint won't be changed/overwritten with None 
    changes = update_data.model_dump(exclude_unset=True)

    for field_name, field_value in changes.items():
        setattr(
            complaint,
            field_name,
            field_value,
        )
    db.commit()
    db.refresh(complaint)
    
    return complaint

def update_complaint_fields(
        db:Session,
        complaint: Complaint,
        changes: dict,
) -> Complaint:
    """
    CNU
    Update selected structured fields on a complaint.

    Only keys supplied in changes are modified
    """

    allowed_fields = {
        "summary",
        "category",
        "city",
        "area",
        "pincode",
        "status",
        "email_subject",
        "email_body",
    }

    for field_name, field_value in changes.items():
        if field_name not in allowed_fields:
            raise ValueError(
                f'Unsupported complaint field: {field_name}'
            )
        setattr(
            complaint,
            field_name,
            field_value,
        )
    db.commit()
    db.refresh(complaint)

    return complaint 

def save_complaint_email_draft(
        db:Session,
        complaint: Complaint,
        subject: str,
        body: str,
) -> Complaint:
    """
    Saving a generated email subject + body

    The complaint remains awaitign approval until user
    give it's ok
    """
    complaint.email_subject = subject
    complaint.email_body = body

    db.commit()
    db.refresh(complaint)

    return complaint

def update_complaint_email_draft(
        db: Session,
        complaint: Complaint,
        subject: str,
        body:str,
) -> Complaint:
    """
    Save changes made by user to the draft email

    Editing the draft won't approve it. The status will still
    be awaiting approval
    """
    complaint.email_subject = subject
    complaint.email_body = body

    db.commit()
    db.refresh(complaint)

    return complaint

def approve_complaint_email_draft(
        db:Session,
        complaint: Complaint,
) -> Complaint:
    """
    We will mark current email draft as approved by the user

    Will check if the body and subject are present or not
    """

    if not complaint.email_subject:
        raise ValueError(
            "The complaint doesn't have a email subject."
        )
    if not complaint.email_body:
            raise ValueError(
                "The complaint doesn't have a email body."
            )
        
    complaint.status = ComplaintStatus.APPROVED

    db.commit()
    db.refresh(complaint)

    return complaint