from datetime import datetime, timedelta, timezone

import pytest
from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from app.database.models import GmailOAuthState, User
from app.database.session import SessionLocal
from app.services.gmail_oauth_state import (
    InvalidOAuthStateError,
    consume_oauth_state,
    create_oauth_state,
    hash_oauth_state,
)
from app.utils.security import hash_password


TEST_EMAIL = "oauth-state-test@example.com"


@pytest.fixture
def db_session():
    """
    Provide a real database session and clean temporary test records.
    """

    db = SessionLocal()

    try:
        db.execute(
            delete(User).where(
                User.email == TEST_EMAIL,
            )
        )
        db.commit()

        yield db

    finally:
        db.rollback()

        db.execute(
            delete(User).where(
                User.email == TEST_EMAIL,
            )
        )
        db.commit()
        db.close()


def create_test_user(
        db: Session,
) -> User:
    """
    Create the Public Pulse user that starts the OAuth flow.
    """

    user = User(
        name="OAuth State Test",
        email=TEST_EMAIL,
        phone="9111111111",
        hashed_password=hash_password(
            "test-password",
        ),
    )

    db.add(user)
    db.commit()
    db.refresh(user)

    return user


def test_create_and_consume_oauth_state(
        db_session,
) -> None:
    """
    A valid state should return the initiating user's ID.
    """

    user = create_test_user(db_session)

    state = create_oauth_state(
        db=db_session,
        user_id=user.id,
    )

    returned_user_id = consume_oauth_state(
        db=db_session,
        state=state,
    )

    assert returned_user_id == user.id


def test_plain_state_is_not_stored(
        db_session,
) -> None:
    """
    PostgreSQL should contain only the SHA-256 state hash.
    """

    user = create_test_user(db_session)

    state = create_oauth_state(
        db=db_session,
        user_id=user.id,
    )

    stored_state = db_session.execute(
        select(GmailOAuthState)
    ).scalar_one()

    assert stored_state.state_hash != state
    assert stored_state.state_hash == hash_oauth_state(state)


def test_oauth_state_cannot_be_used_twice(
        db_session,
) -> None:
    """
    A consumed state must be rejected on a second callback.
    """

    user = create_test_user(db_session)

    state = create_oauth_state(
        db=db_session,
        user_id=user.id,
    )

    consume_oauth_state(
        db=db_session,
        state=state,
    )

    with pytest.raises(
        InvalidOAuthStateError,
        match="already been used",
    ):
        consume_oauth_state(
            db=db_session,
            state=state,
        )


def test_unknown_oauth_state_is_rejected(
        db_session,
) -> None:
    """
    A state not generated by Public Pulse must be rejected.
    """

    with pytest.raises(
        InvalidOAuthStateError,
        match="invalid",
    ):
        consume_oauth_state(
            db=db_session,
            state="attacker-created-state",
        )


def test_expired_oauth_state_is_rejected(
        db_session,
) -> None:
    """
    Expired states must not identify or authorize a user.
    """

    user = create_test_user(db_session)

    state = "expired-state-value"

    expired_state = GmailOAuthState(
        user_id=user.id,
        state_hash=hash_oauth_state(state),
        expires_at=(
            datetime.now(timezone.utc)
            - timedelta(minutes=1)
        ),
    )

    db_session.add(expired_state)
    db_session.commit()

    with pytest.raises(
        InvalidOAuthStateError,
        match="expired",
    ):
        consume_oauth_state(
            db=db_session,
            state=state,
        )