"""add city id to complaints

Revision ID: 24adc968576f
Revises: b42879d2f486
Create Date: 2026-07-29 22:58:43.944345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24adc968576f'
down_revision: Union[str, Sequence[str], None] = 'b42879d2f486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('city_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_complaints_city'), table_name='complaints')
    op.create_foreign_key(None, 'complaints', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_index(op.f('ix_complaints_city'), 'complaints', ['city'], unique=False)
    op.drop_column('complaints', 'city_id')
    # ### end Alembic commands ###
