"""add code verifier to gmail oauth states

Revision ID: 63a7b3e22fc1
Revises: fb1f56105f83
Create Date: 2026-08-07 19:52:15.603583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a7b3e22fc1'
down_revision: Union[str, Sequence[str], None] = 'fb1f56105f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_oauth_states', sa.Column('code_verifier', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_oauth_states', 'code_verifier')
    # ### end Alembic commands ###
