"""link complaints to authorities

Revision ID: 687cfb29c20e
Revises: fa6e081c3b71
Create Date: 2026-07-30 18:33:17.857631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687cfb29c20e'
down_revision: Union[str, Sequence[str], None] = 'fa6e081c3b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('authority_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_complaints_authority_id'), 'complaints', ['authority_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'authorities', ['authority_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_authority_id'), table_name='complaints')
    op.drop_column('complaints', 'authority_id')
    # ### end Alembic commands ###
