"""create complaint conversation tables

Revision ID: d6afce2275e6
Revises: 40c7d3c22aa5
Create Date: 2026-07-26 14:20:28.107274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6afce2275e6'
down_revision: Union[str, Sequence[str], None] = '40c7d3c22aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('road', 'water', 'electricity', 'sanitation', 'police', 'government_school', 'women_safety', 'child_labour', 'overpricing', 'other', name='complaint_category', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('status', sa.Enum('draft', 'awaiting_approval', 'sent', 'unresolved', 'partially_resolved', 'resolved', name='complaint_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_city'), 'complaints', ['city'], unique=False)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_pincode'), 'complaints', ['pincode'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_user_id'), 'complaints', ['user_id'], unique=False)
    op.create_table('complaint_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='complaint_messag_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_messages_complaint_id'), 'complaint_messages', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_messages_id'), 'complaint_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_messages_id'), table_name='complaint_messages')
    op.drop_index(op.f('ix_complaint_messages_complaint_id'), table_name='complaint_messages')
    op.drop_table('complaint_messages')
    op.drop_index(op.f('ix_complaints_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_pincode'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_city'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
