"""add gmail credentials table

Revision ID: d77f0912bced
Revises: 687cfb29c20e
Create Date: 2026-08-06 00:50:46.837336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77f0912bced'
down_revision: Union[str, Sequence[str], None] = '687cfb29c20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_account_id', sa.String(length=255), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_credentials_google_account_id'), 'gmail_credentials', ['google_account_id'], unique=True)
    op.create_index(op.f('ix_gmail_credentials_id'), 'gmail_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_gmail_credentials_user_id'), 'gmail_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_credentials_user_id'), table_name='gmail_credentials')
    op.drop_index(op.f('ix_gmail_credentials_id'), table_name='gmail_credentials')
    op.drop_index(op.f('ix_gmail_credentials_google_account_id'), table_name='gmail_credentials')
    op.drop_table('gmail_credentials')
    # ### end Alembic commands ###
