"""create authorities table

Revision ID: fa6e081c3b71
Revises: 24adc968576f
Create Date: 2026-07-30 12:17:11.782232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6e081c3b71'
down_revision: Union[str, Sequence[str], None] = '24adc968576f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('road', 'water', 'electricity', 'sanitation', 'police', 'government_school', 'women_safety', 'child_labour', 'overpricing', 'other', name='authority_complaint_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'pincode', 'category', name='uq_authority_city_pincode_category')
    )
    op.create_index(op.f('ix_authorities_category'), 'authorities', ['category'], unique=False)
    op.create_index(op.f('ix_authorities_city_id'), 'authorities', ['city_id'], unique=False)
    op.create_index(op.f('ix_authorities_pincode'), 'authorities', ['pincode'], unique=False)
    op.create_index(op.f('ix_complaints_city'), 'complaints', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_city'), table_name='complaints')
    op.drop_index(op.f('ix_authorities_pincode'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_city_id'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_category'), table_name='authorities')
    op.drop_table('authorities')
    # ### end Alembic commands ###
