"""add gmail oauth states table

Revision ID: fb1f56105f83
Revises: cc01272efb4e
Create Date: 2026-08-06 14:43:14.303010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1f56105f83'
down_revision: Union[str, Sequence[str], None] = 'cc01272efb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_oauth_states_id'), 'gmail_oauth_states', ['id'], unique=False)
    op.create_index(op.f('ix_gmail_oauth_states_state_hash'), 'gmail_oauth_states', ['state_hash'], unique=True)
    op.create_index(op.f('ix_gmail_oauth_states_user_id'), 'gmail_oauth_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_oauth_states_user_id'), table_name='gmail_oauth_states')
    op.drop_index(op.f('ix_gmail_oauth_states_state_hash'), table_name='gmail_oauth_states')
    op.drop_index(op.f('ix_gmail_oauth_states_id'), table_name='gmail_oauth_states')
    op.drop_table('gmail_oauth_states')
    # ### end Alembic commands ###
